apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- auth-authorizationpolicy.yaml
- auth-certificate.yaml
- auth-gateway.yaml
- secret.yaml
- oauth2-signout-virtual-service.yaml
