apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
    archiveLogs: true
    s3:
      bucket: babylon2-pipelines
      keyPrefix: pipelines/artifacts
      endpoint: s3.amazonaws.com
      region: us-west-2
      insecure: false
  containerRuntimeExecutor: pns
  # namespace: kubeflow
  # executorImage: gcr.io/ml-pipeline/argoexec:v2.7.5-license-compliance
