apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::562046374233:role/eksctl-babylon-2-addon-iamserviceaccount-cer-Role1-U4HWVK01B4N2
