apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.9.2
    chart: cluster-autoscaler
    helm:
      parameters:
        - name: rbac.serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::562046374233:role/eksctl-babylon-2-addon-iamserviceaccount-kub-Role1-ZQIUO0E5RH40
        - name: rbac.serviceAccount.create
          value: "true"
        - name: rbac.create
          value: "true"
        - name: fullnameOverride
          value: cluster-autoscaler
        - name: cloudProvider
          value: aws
        - name: image.repository
          value: us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler
        - name: image.tag
          value: v1.20.0
        - name: autoDiscovery.clusterName
          value: babylon-2
        - name: autoDiscovery.enabled
          value: "true"
        - name: awsRegion
          value: us-west-2
        - name: extraArgs.balance-similar-node-groups
          value: "true"
        - name: extraArgs.scale-down-enabled
          value: "true"
        - name: rbac.create
          value: "true"
        - name: rbac.pspEnabled
          value: "true"
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
