apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/argoflow-aws.git
    targetRevision: babylon2
    path: distribution/kubeflow/pipelines/s3/base
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
