kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: babylon-2.cxyfjtn0i4xd.us-west-2.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: babylon2-mlflow
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
