apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: mlflow-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: mlflow.babylon2.beyond.ai
  dnsNames:
    - mlflow.babylon2.beyond.ai
