kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-s3-config
  namespace: kubeflow
data:
  REGION: us-west-2
  BUCKET_NAME: babylon2-pipelines
  PIPELINE_FOLDER: pipelines
  PIPELINE_PATH: pipelines
