apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: edit
    user: mshirdel@beyond.ai
  name: user-mshirdel-beyond-ai-clusterrole-edit
  namespace: mlgroup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: mshirdel@beyond.ai

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: edit
    user: mshirdel@beyond.ai
  name: user-mshirdel-beyond-ai-clusterrole-edit
  namespace: mlgroup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: mshirdel@beyond.ai